# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-05-22 13:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('navbar', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='navbarentry',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='navbarentry',
            name='parent',
        ),
        migrations.DeleteModel(
            name='NavBarEntry',
        ),
    ]
